### ISSUE TITLE
Exceptions thrown in production

### ISSUE THREAD

**Issue by dereuromark** [ADmad/CakePHP-HybridAuth#94] opened 2017-02-17 10:46 UTC
### Steps Done

'ADmad/HybridAuth.HybridAuth' added to Auth component 'authenticate'

Users Table initialize():

        $this->hasMany('ADmad/HybridAuth.SocialProfiles');
        EventManager::instance()->on('HybridAuth.newUser', [$this, 'createUser']);

That createUser returns `return $result;` entity always.

### Problem
For initial user login (not in DB yet) we always get an exception from https://github.com/ADmad/CakePHP-HybridAuth/blob/master/src/Auth/HybridAuthAuthenticate.php#L339
But everything seems to be still working, commenting it out and it all works fine.
Still not sure why this is happening, or if/why this executes multiple times here.

Can we make the exception optional or configurable so there is a way to have this not fail on production for every new user, especially since this exception seems to be only overprotective and it all works fine without this being thrown. We could also do this for debug mode only maybe?

**Comment by sufyan297** [comment] 2017-02-22 02:38
i got this problem too there is something wrong with EventManager in 3.4 It does not give time to create User in table. instead it directly throws exception.
But my Model createUser() execute but after this exception throws. so after 2nd time i tried to login it will successfully logged in.  Because it found user record in table. which is created lately when we logged in for the first time.

So i just wasted my whole day to figure out this thing.. then for temp solution....
in HybridAuthAuthenticate.php there is one method **protected function _getUser($adapter)** which is checking whether user is exists or not if not exists then it throws this Exception.

So if user is not found, i created my user account there just only with Email.

```
if (!$user) {
            //UserNotFound Create One
            $userEntity = $this->_userModel->newEntity(['username'=>$profile->email, 'email' => $profile->email]);
            $user = $this->_userModel->save($userEntity);
}
```

This is just temp fix i am also hoping for permanently fixed...

**Comment by ADmad** [comment] 2017-02-22 05:38
Does this issue occur for every new user or it occurs intermittently?

>  It does not give time to create User in table. instead it directly throws exception.

Well event handling isn't asynchronous so I don't understand how that would happen.

**Comment by sufyan297** [comment] 2017-02-22 05:43
Yes it occurs for every new user...

**Comment by ADmad** [comment] 2017-02-22 06:25
Okay I am able to reproduce the issue. The problem is due to a regression in `Cake\Event\Event`. In 3.3 the result of listener was set to public property `Event::$result`. In 3.4 #9376 removed the public property and replaced it with protected `$_result` which is causing the problem.

**Comment by ADmad** [comment] 2017-02-22 07:18
Closing as PR to fix the root cause of the issue in core has been opened. No change is necessary in the plugin.

**Closed by ADmad** 2017-02-22 07:18 UTC

**Comment by dereuromark** [comment] 2017-02-22 10:02
Thanks a lot for looking into it!

**Comment by dereuromark** [comment] 2017-02-22 10:03
Will you release a new version/tag for Cakephp 3.x?
